---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: local
      hooks:

          - id: ruff
            name: Check with Ruff
            entry: poetry run ruff
            language: system
            pass_filenames: false
            always_run: true
            args: ["check", "backend", "tests", "--fix"]

          - id: mypy
            name: Validate types with MyPy
            entry: poetry run mypy
            language: system
            types: [python]
            pass_filenames: false
            args:
              - "backend"
