services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: backend:${BACKEND_VERSION:-latest}
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      BACKEND_HOST: 0.0.0.0
      BACKEND_DB_HOST: backend-db
      BACKEND_DB_PORT: 27017
      BACKEND_DB_USER: backend
      BACKEND_DB_PASS: backend
      BACKEND_DB_BASE: admin
  db:
    image: mongo:7.0
    hostname: backend-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "backend"
      MONGO_INITDB_ROOT_PASSWORD: "backend"
    command: "mongod"
    volumes:
      - backend-db-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 40

volumes:
  backend-db-data:
    name: backend-db-data
